### ISSUE TITLE
Despite Doctype being at the top of the page with nothing declared first, still getting the error

### ISSUE THREAD

**Issue by Georgiel** [AtomLinter/linter-htmlhint#102]
![image](https://cloud.githubusercontent.com/assets/5931248/14675363/999727cc-0700-11e6-9b9c-69269ba218da.png)

This a bug or is linter-htmlhint not playing nice with another plugin?

**Comment by Arcanemagus** [comment]
What error are you seeing? None are shown in your screenshot...

**Comment by Georgiel** [comment]
Oops.

The error is
```Line 1 Column 1 "DOCTYPE must be at top of page."```

Kind Regards,

George W Langham
On 20 Apr 2016 6:54 p.m., "Landon Abney" <notifications@github.com> wrote:

What error are you seeing? None are shown in your screenshot...

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/AtomLinter/linter-htmlhint/issues/102#issuecomment-212534501>

**Comment by Arcanemagus** [comment]
If you run `htmlhint` from the command line does it show the same error?

**Comment by Georgiel** [comment]
I have yet to, but when looked on other forums a great many mentioned it.

**Comment by Arcanemagus** [comment]
@Georgiel any update? Also can you try v1.2.0 as it changes the way that HTMLHint is being ran.

**Comment by Georgiel** [comment]
@Arcanemagus I think it looks to have been solved with that version.

**Comment by Arcanemagus** [comment]
Awesome, glad to hear it.
