### ISSUE TITLE
how to enable lintOnFly ?

### ISSUE THREAD

**Issue by atoy40** [AtomLinter/linter-htmlhint#105]
Hello,

I'd like to know why you choose to disable the onFly "linting" on html, and more important to me, is it possible to enable it without modifying the code ? I've tried some syntaxes in my cson file without success.

note: lintOnFly is activated for the linter package

Thanks
Anthony.

**Comment by Arcanemagus** [comment]
Looks like this was changed in the re-write due to [this comment](https://github.com/AtomLinter/linter-htmlhint/pull/63#discussion_r49100906) of mine. So I'm assuming I tested `htmlhint` and found it couldn't accept input via `stdin`.

Does `cat foo.html | htmlhint` work for you?

**Comment by Arcanemagus** [comment]
Hmmm, looks like that actually _does_ work, so I'm not sure why I made that comment :confused:.

**Comment by Arcanemagus** [comment]
Ah ha, the old code had `lintOnFly` set to true, but wasn't actually passing in the contents so it was _triggering_ all the time, but was only running on the saved contents.

I'll get a fix up shortly.

**Comment by Arcanemagus** [comment]
Ah, okay nevermind. `htmlhint` by default scans the current directory which is why it just looked like it was working... it's completely ignoring `stdin`.

```shellsession
PS C:\Temp\github> cat .\linter-htmlhint_GH104\linter-error.html | node .\linter-htmlhint_GH104\node_modules\htmlhint\bin\htmlhint

   linter-bootlint_GH20/karunamon.html
      L1 |<div class="form-group">
          ^ Doctype must be declared first. (doctype-first)

   linter-bootlint_GH34/basic.html
      L5 |</head>
          ^ <title> must be present in <head> tag. (title-require)
.....

Scan 10 files, found 172 errors in 9 files (502 ms)
```

**Comment by Arcanemagus** [comment]
Looks like https://github.com/yaniswang/HTMLHint/issues/97 is the issue to follow for this.
