### ISSUE TITLE
Why a subprocess?

### ISSUE THREAD

**Issue by download13** [AtomLinter/linter-htmlhint#111]
Is there any particular reason this is running HTMLHint as a subprocess?

HTMLHint has an [internal API](https://github.com/yaniswang/HTMLHint/blob/master/src/core.js) that is used by [it's command line script](https://github.com/yaniswang/HTMLHint/blob/master/bin/htmlhint). linter-htmlhint could make use of the API, which would likely be faster and less memory intensive. Additionally, it would allow live linting without having to save the file.

Has this idea been considered and rejected before, or is it a possibility for some future release?

**Comment by Arcanemagus** [comment]
I'm assuming it is done that way to avoid having to deal with loading and parsing the `.htmlhintrc` files manually, then sending that configuration on to the Node API. It doesn't help that [the documentation](https://github.com/yaniswang/HTMLHint/wiki/Usage#javascript-with-node) is... _sparse_ to say the least. You would have to ask @johnwebbcole as to the original reasoning.

If you want to put together a PR switching over to that it sounds like it would be beneficial.

**Comment by download13** [comment]
That was surprisingly straightforward.

**Comment by Arcanemagus** [comment]
Merged 🎉.
