### ISSUE TITLE
SyntaxError: Unexpected end of input on custom rule

### ISSUE THREAD

**Issue by igorleao** [AtomLinter/linter-htmlhint#114]
Hi everyone,

I decided to create some custom rules, which work fine on linting both .html and .html.erb files.
One specific rule is not working very well, though. This rule attempts to lint empty lines:

```
module.exports = function(HTMLHint) {
  HTMLHint.addRule({
      id: 'no-empty-line',
      description: 'Detect empty lines.',
      init: function(parser, reporter){
          var self = this;
          parser.addListener('tagstart tagend comment text', function(event){
              lastEvent = event.lastEvent;
              if(lastEvent.raw && lastEvent.raw.toLowerCase().indexOf("\n\n") != -1) {
                for(i=lastEvent.line+1; i<event.line; i++) {
                    reporter.warn('Remove empty line.', i, 0, self, event.raw);
                }
              }
          });
      }
  });
}
```

The idea behind the code above is to detect multiple \n on an previous event and send a warning to all lines in between the previous and the current event. It works fine with a few empty lines. However, if the file contains several empty lines one after another, it crashes, reporting: ```"SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Users/igorleao/Bitbucket/htmlhint-atom/lib/index.js:61:30"```. 
Line 61 on index.js contains: `const results = JSON.parse(output);`

I'm confused if it's an error on my implementation or if it's some unexpected behaviour, once it's a bit weird.

I've cloned the master of this repository and installed using npm install and apm link.

Versions:
htmlhint: 0.9.13
atom 1.8.0
linter 1.11.4
linter-htmlhint 1.1.4
 
Thanks a lot!!

Here you are some inputs:
1. works fine
```
<!DOCTYPE html>
<html>
  <body>

		
  </body>
</html>
```
2. crashes
```
<!DOCTYPE html>
<html>
	<body>




































  </body>
</html>
```

**Comment by igorleao** [comment]
PS: I notice it's beyond my rule. This error happens with some files and doesn't happen with others and seems to happen or not depending on the rule you use.

**Comment by Arcanemagus** [comment]
What does `htmlhint` show from the CLI?

**Comment by igorleao** [comment]
It seems to have no problem at all

```
Ins-Mac-mini% ./htmlhint --config /Users/igor/GitHub/test/.htmlhintrc --rules-dir /Users/igor/GitHub/test/rules /Users/igor/GitHub/test/teste.html.erb

   Config loaded: /Users/igor/GitHub/test/.htmlhintrc

Scanned 1 files, no errors found (18 ms).
```

.htmlhintrc
````
{
  "no-empty-line": true
}
```

changes on htmlhint-plugin/index.js to load custom rules:

````
      const parameters = [filePath, '--format', 'json'];
      const htmlhintrc = find(path.dirname(filePath), '.htmlhintrc');
      
      // begin changes
      const rules      = find(path.dirname(filePath), 'rules/');
      parameters.push('--rulesdir');
      parameters.push(rules);
      // end changes

      if (htmlhintrc) {
        parameters.push('-c');
        parameters.push(htmlhintrc);
      }
```

Thanks a lot!

**Comment by Arcanemagus** [comment]
Closing, #112 should make this irrelevant.

I'll be releasing a new version including that shortly!

**Comment by Arcanemagus** [comment]
Closing, #112 should make this irrelevant.

I'll be releasing a new version including that shortly!
