### ISSUE TITLE
Angular 2 issue

### ISSUE THREAD

**Issue by ketchup201** [AtomLinter/linter-htmlhint#135]
Hey, this plugin is EXACTLY what I've been looking for! It works almost too well, though. I'm using angular2, and have an html attribute with no value:

\<template ngSwitchDefault\>
it gives me a warning that I need to supply a value for the attribute.

Is there a setting I can put in that will forgive this issue ?

**Comment by Arcanemagus** [comment]
Unfortunately your only option is to either disable this package on Angular files, or to disable the rule checking that using a `htmlhint.conf` file which disables the specific rule giving you that error. YOu can find a list of the rules [here](https://github.com/yaniswang/HTMLHint/wiki/Rules).

**Comment by johnwebbcole** [comment]
I'd recommend creating an issue with [htmlhint](https://github.com/yaniswang/HTMLHint/issues)

When creating a .htmlhintrc file, I usually start with [htmlhint.com](http://htmlhint.com) and check everything, then turn off the things that are annoying.  If you use a .htmlhintrc file, htmlhint will ONLY check for the things that are turned on, at least it has done this in the past.  Things change rapidly.

I'm expecting a lot of questions about [Angular2](http://eisenbergeffect.bluespire.com/on-angular-2-and-html/) and htmlhint (this isn't the first one), and it would be nice to have a good workflow to point to.
