### ISSUE TITLE
Request: scan hierarchically for .htmlhintrc

### ISSUE THREAD

**Issue by nelsonmenezes** [AtomLinter/linter-htmlhint#15]
The current implementation loads options from a .htmlhintrc file in the same directory. It would be great if it could scan for this file upwards through the directory structure, at least up to the project root (or, even better, up to the system root).

**Comment by brunowego** [comment]
+1

**Comment by johnwebbcole** [comment]
I thing it already does this.  The findFile helper used to locate the `.htmlhintrc` file searches up the directory tree.

**Comment by johnwebbcole** [comment]
I have multiple .htmlhintrc files in my projects and linter-htmlhint seems to find them ok.  For example, I have one in my views directory and editing files in directories below that use that `.htmlhintrc` (it's the one with the doctype check false).
