### ISSUE TITLE
doesn't recognize .html files using Jekyll

### ISSUE THREAD

**Issue by yochem** [AtomLinter/linter-htmlhint#155]
All my files are named like a normal html-file: name.html, index.html etc. 
But because I use the [jekyll-atom package](https://github.com/arcath/jekyll-atom) Atom detects it as a 'jekyll (HTML)' file:

![screenshot](https://cloud.githubusercontent.com/assets/23235841/24524678/c507037c-1597-11e7-81bc-873ba55bdc15.png)

Because of this, htmlhint won't run onto these files. If I click on 'Jekyll (HTML)' and change it to HTML it works just fine. Is it possible to fix this? 

Thank you!

**Comment by ricardograca** [comment]
Maybe ask the jekyll-atom authors to not mark html files as `Jekyll (HTML)`? Or there could be a configuration option in that package to do that already.

**Comment by Arcanemagus** [comment]
As @ricardograca said either get `jekyll-atom` to not mark everything as "Jekyll (HTML)" (which isn't "HTML"!), or as of v1.3.0 and later you can add that scope to the list of scopes that are linted in the "Enabled Scopes" setting.

**Comment by yochem** [comment]
thank you!
