### ISSUE TITLE
Editor flickers in short burst with white blocks whenever  I start typing but not while scrolling

### ISSUE THREAD

**Issue by NeetishRaj** [AtomLinter/linter-htmlhint#171]
System specs: OS Ubuntu 16.04 ,4GB RAM, DDR3 disk, ASUS K55VD
Atom version : 1.21.0
linter-htmlhint version: 1.4.0

It only **started after installing linter-htmlhint and in html tabs**, and whenever entering text then white blocks appear in short bursts, but it does not happens while cursor scrolling and only when I start typing in the html file.

**Comment by NeetishRaj** [comment]
atom version is 1.21.0
linter version 2.2.0
linter-ui-default version 1.6.10
linter-htmllint version 1.4.0
linter-csslint version 2.0.0
HTML file tabs in editor flickers in short bursts ( white blocks appear for very short time), whenever text is entered , it started happening when i installed linter plugin, its dependecy linter-ui-deault, lintercss and linterhtml.
Flickering happens while

starting to enter text
saving the file with CTRL + S
selecting all with CTRL + A
and only for html and css files, and I am using linter for only these two, no issues in javascript files for which I have disabled linter

**Comment by Arcanemagus** [comment]
As stated in the `linter` issue you commented on, this is a bug with the Intel graphics driver. We aren't sure why it seems to start triggering with `linter-ui-default`, but it isn't something that can be controlled here. There are instructions there to switch away from this buggy driver.
