### ISSUE TITLE
Support htmllint as well?

### ISSUE THREAD

**Issue by ericcornelissen** [AtomLinter/linter-htmlhint#174]
I recently discovered an alternative to [htmlhint](https://www.npmjs.com/package/htmlhint) called [htmllint](https://github.com/htmllint/htmllint) which I personally prefer because of its ruleset. I was wondering if the maintainers of this package would be interested in supporting both of them?

If so, one possible implementation could be that there is an option to either `use htmlhint`, `use htmllint` or `detect which one to use` (default). If the last value is selected, this package will use either htmlhint or htmllint based on the configuration file found in the project.

Thoughts?

**Comment by Arcanemagus** [comment]
It's generally better to keep providers focused on a specific linter they are wrapping around, that way better support for the options of that specific tool and handling of it's output can be managed.

You're welcome to create a new provider for `htmllint`! Feel free to use any of the the providers here as a base. If you do write up a provider I'd be happy to have it here in the AtomLinter organization so others can work on it as well if you want 😉.

If you have any questions feel free to message me on [Atom's Slack](https://discuss.atom.io/t/join-us-on-slack/16638).
