### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by smlombardi** [AtomLinter/linter-htmlhint#26]
I have atom-linter 1.1.0 and a few linters, and they work fine.

I realized I don't have any html linter so I installed this.  I also installed `npm install htmlhint`, so now `which htmlhint` which gives me `/usr/local/bin/htmlhint`.

So, I opened my config and made sure I had
````
  "linter-htmlhint":
    htmlhintExecutablePath: "/usr/local/bin/htmlhint"
````
But I get no error flagging.  What m I missing?

**Comment by johnwebbcole** [comment]
I think this has to do with there being more than one text.html syntax type.  You can check this by making sure your grammar is set to `HTML` rather than `HTML (Angular)` or whatnot...

I'm adding the other html types now.
