### ISSUE TITLE
Trouble customizing

### ISSUE THREAD

**Issue by adamzerner** [AtomLinter/linter-htmlhint#30]
```
  "linter-htmlhint":
    attrValueDoubleQuotes: false
```

isn't working for me in `config.cson`. Can you override such properties? I don't see anything that says you could in the [README](https://github.com/AtomLinter/linter-htmlhint#settings).

I got the property from [htmlhint](https://github.com/yaniswang/HTMLHint/wiki/Attr-value-double-quotes). I changed it to camelCase because Atom gave me an error when I tried to save it as dash-cased.

- - -

I know it says

```
'linter-htmlhint':
  'htmlhintExecutablePath': null #htmlhint path. run 'which htmlhint' to find the path
```

but when I run `which htmlhint`, I don't get anything. I even tried running `apm install linter-htmlhint`, and the `which htmlhint` command still didn't do anything for me.

**Comment by johnwebbcole** [comment]
You can customize how htmlhint works by using a `.htmlhintrc` file.  See the htmlhint documentation for more info.  If you don't install htmlhint globally, it won't be in your path.  By default, linter-htmlhint will use the version installed with the plugin.

**Comment by adamzerner** [comment]
Where would I put the `.htmlhintrc` file such that it'd be used for everything? Somewhere in `.atom`?

**Comment by coliff** [comment]
You put the .htmlhintrc in the root folder of your project. It's explained here:
https://github.com/yaniswang/HTMLHint/wiki/Usage#about-htmlhintrc

**Comment by Arcanemagus** [comment]
Marking as closed since this isn't really an issue with `linter-htmlhint`. Feel free to comment back or file a new issue if you feel otherwise.
