### ISSUE TITLE
validate on save only, not on the fly

### ISSUE THREAD

**Issue by adarrra** [AtomLinter/linter-htmlhint#34]
Hi! I don't know why it validate only on save. 
Atom 1.0.11
In my config.cson: 
```CSON
htmlhint:
    validateOnChange: true
    validateOnSave: false
```

**Comment by johnwebbcole** [comment]
I think this is an option on linter, not linter-htmlhint.

**Comment by adarrra** [comment]
no, linter works on change with linter-jshint, and have enabled setting "check on the fly"

**Comment by adarrra** [comment]
I am noticed that on my laptop everything works fine. I have ubuntu 14.04 on both device.  But on working computer some more packages work buggy. I don't know how can I debug this. Maybe some advices?

**Comment by johnwebbcole** [comment]
Looking at the source of `linter-jshint` I only see three options: executablePath, lintInlineJavaScript and disableWhenNoJshintrcFileInPath.

The lintOnFly internal option for the provider is set to true for both `linter-jshint` and `linter-htmlhint`
