### ISSUE TITLE
Linter html markup inside *.php file

### ISSUE THREAD

**Issue by PixelT** [AtomLinter/linter-htmlhint#35]
It's possible to lint the HTML markup inside the *.php file?

**Comment by johnwebbcole** [comment]
Linting is done by `htmlhint`, `linter-htmlhint` is a wrapper around that utility.  I'm not sure if it will do that or not.  You might see if there are some php linters supported by the `linter` framework.

**Comment by Arcanemagus** [comment]
If your cursor is within a HTML section when you trigger the lint this _should_ at least try to run it through `htmllint`, whether that itself can extract the HTML part and lint that is another story.
