### ISSUE TITLE
Linter say < > must be  escaped

### ISSUE THREAD

**Issue by taaem** [AtomLinter/linter-htmlhint#4]
The Linter says that the opening '<' and the closing '>' of a link element must be escaped but it's only normal html syntax which can't be escaped. Only happens with two links which refer to Google Fonts in my header. 
I can live with ignoring that error but still wanted to report it.
![linter error](https://cloud.githubusercontent.com/assets/7108647/5705767/ff0df1be-9a7b-11e4-9a3d-1bc3bc812650.png)

**Comment by dmnd** [comment]
This is an issue with the underlying linter, not the Atom plugin - please report it to htmlhint
