### ISSUE TITLE
Error:  Unexpected end of input

### ISSUE THREAD

**Issue by smlombardi** [AtomLinter/linter-htmlhint#41]
Atom 1.10 beta 1 or 1.0.19, linter-htmlhint 0.2.0

Gives this error instantly:

<img width="462" alt="screen shot 2015-10-24 at 4 01 39 pm" src="https://cloud.githubusercontent.com/assets/835148/10712416/e2f23a80-7a68-11e5-9f17-9d0b15f25337.png">

**Comment by johnwebbcole** [comment]
Could you give a few more details... what kind of file are you editing, what OS.

I'm not seeing any issues on 1.0.19 and linter-htmlhint 0.2.0 on OSX

**Comment by smlombardi** [comment]
I was editing a PHP file on Mac 10.11.1.  The dialogs would just pop up as
I edited and I needed to disable.

I'll try again when I go to work Monday with more traditional HTML/Angular
JS files.  This weekend I have a rare Wordpress project.

Thanks

**Comment by jefkoslowski** [comment]
Same here, editing a PHP file.

Atom 1.0.19
linter-htmlhint 0.2.0
OS X El Capitan

**Comment by woodland021** [comment]
+1 Same here, editing a PHP file.

Atom 1.0.19
linter htmlhint 0.2.0
OS X El Capitan
