### ISSUE TITLE
.htmlhintrc parsing issue

### ISSUE THREAD

**Issue by Hufschmidt** [AtomLinter/linter-htmlhint#48]
It seems like parsing of .htmlhintrc is broken with linter-htmlhint.

# Issue:
    {
      "doctype-first": false
    }

No linting happens in Atom, but using this file with gulp-htmlhint works just fine...

    {
      "doctype-first": false,
    }

Linting in atom using linter-htmlhint works BUT using eg. gulp-htmlhint (for deployment linting via cordova-hook) fails because .htmlhintrc can't be parsed.

Obviously the later is not valid (strict) JSON, so I guess there is an issue with linter-htmlhint when parsing/loading this file. (*htmlhint: 0.9.12 / linter-htmlhint: 0.2.1*)

PS: Might be directly related to #33

**Comment by johnwebbcole** [comment]
`linter-htmlhint` doesn't use the file, it's passed as an argument to htmlhint.

**Comment by Hufschmidt** [comment]
Hm, ok since the valid JSON seemed to work in gulp-htmlhint I guessed linter-htmlhint was trying to do some preproccessing in this file before passing it to htmlhint, my bad.

I tried invoking htmlhint directly, which matched the behavior of linter-htmlhint, so I'll get in contact with htmlhint (and gulp-htmlhint out of curiosity)
