### ISSUE TITLE
Should not lint .vue files

### ISSUE THREAD

**Issue by BlaM** [AtomLinter/linter-htmlhint#49]
Files covered by [language-vue](https://github.com/hedefalk/atom-vue) are using scopeName: "text.html.basic" but should not get a "full" linting. 

A basic lint might be okay (just starting with vue, so I might find out that this assumption is wrong :smile: ), but at least the [doctype-first](https://github.com/yaniswang/HTMLHint/wiki/Doctype-first) rule should be disabled.

**Comment by johnwebbcole** [comment]
You can change the grammar type using the command pallet.  Or you can add a .htmlhintrc file and turn off the doctype check.

**Comment by BlaM** [comment]
Grammar is detected correctly as "Vue Component" (which is at least to some extend a html file). It's still linting as standard HTML.

**Comment by Arcanemagus** [comment]
If you run the `Log Cursor Scope` command, what scopes does it show for this "Vue Component" grammar?

**Comment by BlaM** [comment]
At the top of the file (within actual HTML content):

text.html.basic
meta.tag.any.html
string.quoted.double.html

... or if I move down to a Javascript-Block:

text.html.basic
source.js.embedded.html
meta.import.js
keyword.control.js

--

For Reference: I just tested it in this file (but it's happening in every vue file):

https://github.com/ElvisKang/vue-material/blob/master/src/components/cards/md-basic-card.vue

**Comment by Arcanemagus** [comment]
Looks like this is an issue with language-vue not properly marking the file with a relevant scope, as such Atom is attempting to guess the scope and giving it `text.html.basic`, which this linter says it can handle.

You should report this as an issue over on the language-vue package, as this isn't really a problem with this package I'm marking this as closed.
