### ISSUE TITLE
"Doctype must be declared at first" in Web Components / Polymer

### ISSUE THREAD

**Issue by abdonrd** [AtomLinter/linter-htmlhint#51]
When I create a Web Component with Polymer, I have the error *"Doctype must be declared at first"* always present, because I don't have Doctype.

Any solution to this particular case?

**Comment by johnwebbcole** [comment]
add a .htmlhintrc file and disable that warning.  See the [htmlhint](http://htmlhint.com) page for all the options and a tool to create a .htmlhintrc file.

**Comment by abdonrd** [comment]
But if I do this, I disable for all project, and I have another html files that are not web components.
