### ISSUE TITLE
Inline configuration in HTML files doesn't work

### ISSUE THREAD

**Issue by Bonerdelli** [AtomLinter/linter-htmlhint#55]
I'm try to use this syntax:
```
<!-- htmllint doctype-first="false" -->
```
According to [this manual](https://github.com/htmllint/htmllint/wiki/htmllint-manual#inline-configurations)

**Comment by Arcanemagus** [comment]
Fixed up your URL, markdown has the syntax reversed from how your had it :wink:.

Does this work from the command line `htmlhint`?

**Comment by fdeneux** [comment]
@Bonerdelli you should try:
```
<!-- htmlhint doctype-first="false" -->
```

**Comment by fdeneux** [comment]
@Bonerdelli this should do it:
```html
<!-- htmlhint tag-pair, doctype-first:false -->
```

**Comment by Arcanemagus** [comment]
Thanks for pointing that out @fdeneux! Marking this as closed.
