### ISSUE TITLE
Broken for XHTML5.

### ISSUE THREAD

**Issue by garretwilson** [AtomLinter/linter-htmlhint#58]
I'm using the latest Atom editor version 1.3.1 on Windows 10 Pro 64-bit. I've installed the linter 1.11.3 and linter-htmlhint 0.2.1 plugins.

I'm editing a normal, standards-compliant XHTML5 document that begins like this:

    <?xml version="1.0" encoding="utf-8"?>
    <!DOCTYPE html>
    <html  lang="en-us"  xmlns="http://www.w3.org/1999/xhtml">

linter-htmlhint gives me all sorts of errors:

* Special characters must be escaped : [ < ]. at line 1 col 1
* Special characters must be escaped : [ > ]. at line 1 col 38
* Doctype must be declared first, at line 1 col 1

Has linter-htmlhint never heard of an XML declaration?

Note that XHTML5 is simply the XML serialization of HTML5. For most practical purposes it's pretty much just well-formed HTML with an XML declaration:

http://www.w3.org/TR/html5/introduction.html#html-vs-xhtml

Please provide support for XHTML5.

**Comment by Arcanemagus** [comment]
Does `htmlhint` display the same errors on the command line? This is just a wrapper around that essentially. There have been a multitude of issue with it not properly handling files already so I would not be surprised if it can't handle this properly.

**Comment by Arcanemagus** [comment]
If `htmlhint` on the command line (`npm install -g htmlhint`) shows the same problems you should file an issue [over there](https://github.com/yaniswang/HTMLHint) about it.

**Comment by johnwebbcole** [comment]
You can suppress those errors by turning them off with a .htmlhintrc file.  This plugin is a wrapper around [htmlhint](http://htmlhint.com) and any issues with listing should be reported there.

**Comment by garretwilson** [comment]
Filed https://github.com/yaniswang/HTMLHint/issues/102 with no luck.
