### ISSUE TITLE
syntax error on document save

### ISSUE THREAD

**Issue by citrusui** [AtomLinter/linter-htmlhint#65]
Every time I press save or click CTRL+S to save a document, this pops up. Don't know why. It didn't happen to me in the previous version of `linter-htmlhint`.

![screenshot 13](https://cloud.githubusercontent.com/assets/9056756/12370939/af5efc4c-bbf1-11e5-9f4b-fe7a5f9e9459.png)

**Comment by 1000ch** [comment]
Does it occur after re-installing `linter-htmlhint`?
First look, it seems to be broken.

**Comment by citrusui** [comment]
Yep, reinstalled it and the same error.

**Comment by johnwebbcole** [comment]
Try uninstalling `linter` as well as `linter-htmlhint`, then `install linter-htmlhint`

```
apm uninstall linter linter-htmlhint
apm install linter-htmlhint
```

You can easily reload Atom with <kbd>Ctrl</kbd> + <kbd>Opt</kbd> + <kbd>Cmd</kbd> + <kbd>l</kbd>.

I just unloaded and reloaded all of the `linter` packages and I'm not seeing this error.

**Comment by AlbertoFdzM** [comment]
Same error here.

```
Error: C:\Users\Alberto.atom\packages\linter-htmlhint\node_modules.bin\htmlhint:4 case uname in ^^^^

SyntaxError: Unexpected token case at exports.runInThisContext (vm.js:53:16) at Module._compile (module.js:413:25) at Object.Module._extensions..js (module.js:452:10) at Module.load (module.js:355:32) at Function.Module._load (module.js:310:12) at Function.Module.runMain (module.js:475:10) at startup (node.js:129:18) at node.js:981:3
Error: C:\Users\Alberto\.atom\packages\linter-htmlhint\node_modules\.bin\htmlhint:4
case `uname` in
^^^^

SyntaxError: Unexpected token case
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:129:18)
    at node.js:981:3
    at parameters.exit (C:\Users\Alberto\.atom\packages\linter-csslint\node_modules\atom-linter\lib\helpers.js:75:20)
    at triggerExitCallback (C:\Users\Alberto\AppData\Local\atom\app-1.4.0\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Alberto\AppData\Local\atom\app-1.4.0\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by 1000ch** [comment]
@AlbertoFdzM Would you try reinstall following above the @johnwebbcole's advice?

**Comment by AlbertoFdzM** [comment]
@1000ch I've tried that but still having the error.

More info:
- windows 10
- Atom 1.4.0
- packages:
 - atom-beautify@0.28.21
 - atom-jade@0.3.0
 - atom-ternjs@0.12.2
 - autocomplete-paths@1.0.2
 - color-picker@2.0.14
 - emmet@2.3.17
 - file-icons@1.6.13
 - git-plus@5.12.0
 - highlight-selected@0.11.1
 - html-entities@0.4.0
 - keyboard-localization@1.4.13
 - less-autocompile@1.0.0
 - linter@1.11.3
 - linter-csslint@1.2.0
 - linter-eslint@5.2.7
 - linter-htmlhint@1.0.0
 - linter-jade@0.3.2
 - linter-jscs@3.3.0
 - linter-jshint@1.2.2
 - linter-less@2.3.3
 - merge-conflicts@1.3.7
 - minimap@4.19.0
 - minimap-find-and-replace@4.4.0
 - minimap-git-diff@4.1.8
 - minimap-highlight-selected@4.3.1
 - minimap-selection@4.3.1
 - open-recent@4.0.1
 - pdf-view@0.39.0
 - pigments

**Comment by johnwebbcole** [comment]
Can you run htmlhint from the command line?

```
C:\Users\Alberto\.atom\packages\linter-htmlhint\node_modules\.bin\htmlhint
```

**Comment by AlbertoFdzM** [comment]
Done:
```bash
C:\Users\Alberto\.atom\packages\linter-htmlhint\node_modules\.bin\htmlhint index.html

Scan 1 files, without errors (15 ms).
```

**Comment by johnwebbcole** [comment]
Is this only on Win?  I'm not seeing this on OS X, I'll find a windows box and see if I get the same error.

**Comment by arturparkhisenko** [comment]
Win10 same error (reinstalled linter and linter-htmlhint).

**Comment by KingRial** [comment]
I can confirm the error on Win10 even after reinstalling

**Comment by arturparkhisenko** [comment]
@1000ch i think problem somewhere in this commit (rewrite) https://github.com/AtomLinter/linter-htmlhint/commit/7fa5d8cf3e095ab0b14b5ab56735d856195235d6

**Comment by Arcanemagus** [comment]
@arturparkhisenko if you run the following does the issue go away?

```ShellSession
apm uninstall linter-htmlhint
apm install linter-htmlhint@0.2.2
```

**Comment by efreitasn** [comment]
@Arcanemagus I was getting this error on my w10 then I ran this and it's working again.

**Comment by selkinvitaly** [comment]
@Arcanemagus I had the same error. When I return to 0.2.2 version, the error disappeared. Thanks!

ps win7; node5.4.1; npm 3.3.12

**Comment by KingRial** [comment]
@Arcanemagus I can confirm that installing linter-htmllint@0.2.2 on Windows 10, remove the error.

**Comment by arturparkhisenko** [comment]
@Arcanemagus yep!

**Comment by FuzzyAzurik** [comment]
@Arcanemagus Can confirm installing linter-htmllint@0.2.2 removes the error.

**Comment by garretwilson** [comment]
I just got a big red error after upgrading as well:

	Error: C:\Users\garret.atom\packages\linter-htmlhint\node_modules.bin\htmlhint:4 case uname in ^^^^

	SyntaxError: Unexpected token case at exports.runInThisContext (vm.js:53:16) at Module._compile (module.js:413:25) at Object.Module._extensions..js (module.js:452:10) at Module.load (module.js:355:32) at Function.Module._load (module.js:310:12) at Function.Module.runMain (module.js:475:10) at startup (node.js:129:18) at node.js:981:3

**Comment by fthebaud** [comment]
I'm having the same problem after upgrading on Windows (Windows 7, Atom 1.4, linter-htmlhint 1.0.0).

However, I'm also using Atom with the same configuration (through the sync-settings package) on another computer running Linux  and everything is working fine. (Ubuntu 14.04 LTS, Atom 1.3.2, linter-htmlhint 1.0.0)

**Comment by NoNameProvided** [comment]
Any progress on this?

**Comment by AnWeber** [comment]
hello,the error is happening in the call to execNode in file lib/index.js line 60. Using the method exec instead of execNode fixes the issue on a windows 10 system. [index.txt](https://github.com/AtomLinter/linter-htmlhint/files/99930/index.txt). Sorry I'm in hurry and don't want to fork now.
The difference is that atom-linter is using a [BufferedProcess](https://atom.io/docs/api/v1.4.0/BufferedProcess) instead of a [BufferedNodeProcess](https://atom.io/docs/api/v1.4.0/BufferedNodeProcess) for calling htmlhint.

**Comment by Arcanemagus** [comment]
Wow, that definitely sounds like the issue, thanks for taking the time to trace that down @AnWeber.

@1000ch can you put a fix in for that?

**Comment by 1000ch** [comment]
OK. I've just got a Windows 10 today, I'll try to debug this.

**Comment by arturparkhisenko** [comment]
@AnWeber Thanks! I tested it on Win10x64pro and it's works perfectly :+1:

**Comment by NoNameProvided** [comment]
Awesome! Will anybody make a PR for this?

**Comment by 1000ch** [comment]
↑ I'll fix this, thank you for debugging @AnWeber .

**Comment by 1000ch** [comment]
Please try `v1.0.1`.

**Comment by arturparkhisenko** [comment]
@1000ch all fine :100: thanks!

**Comment by 1000ch** [comment]
@arturparkhisenko Thank you for quick reply :+1:

**Comment by garretwilson** [comment]
I just updated to v1.0.1 and when saving I get:

````
Error: 'node' is not recognized as an internal or external command, operable program or batch file.
Error: 'node' is not recognized as an internal or external command,
operable program or batch file.
    at parameters.exit (C:\Users\garret\.atom\packages\linter-htmlhint\node_modules\atom-linter\lib\helpers.js:75:20)
    at triggerExitCallback (C:\Users\garret\AppData\Local\atom\app-1.4.0\resources\app.asar\src\buffered-process.js:213:47)
    at C:\Users\garret\AppData\Local\atom\app-1.4.0\resources\app.asar\src\buffered-process.js:227:18
    at Socket.<anonymous> (C:\Users\garret\AppData\Local\atom\app-1.4.0\resources\app.asar\src\buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
````

**Comment by arturparkhisenko** [comment]
@garretwilson nodejs is installed? i have installed, maybe thats why i dont get this error

**Comment by NoNameProvided** [comment]
@1000ch Works fine here too! (Win10 Pro 11099)

Thanks for the quick fix! :+1:

**Comment by garretwilson** [comment]
No, I don't have Node installed other than whatever Atom uses behind the scenes. Your plugin shouldn't require it.

**Comment by garretwilson** [comment]
> maybe that's why i can't get this error

Well, there's one way for you to find out: uninstall Node and try it.

**Comment by arturparkhisenko** [comment]
@garretwilson agree with that! Tested.. yes i got this error without nodejs too!

**Comment by AnWeber** [comment]
I think I have found the right way to fix this issue. The path to the htmlhint executable was wrong. I tested this fix on a win10 machine without nodejs:-). Sorry for the previous invalid fix attempt. This fix did just workaround the invalid path. Before releasing, this fix should be tested on a none windows machine.

**Comment by Arcanemagus** [comment]
v1.0.2 is published which should remove the node requirement, please file a new issue if you are continuing to have problems :wink:.
