### ISSUE TITLE
SyntaxError: Unexpected end of input on large files

### ISSUE THREAD

**Issue by fdeneux** [AtomLinter/linter-htmlhint#72]
Hello,

I get this error when opening or saving large .html files. 

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Users/ ... /.atom/packages/linter-htmlhint/lib/index.js:61:30
```

Atom 1.4.1
linter 1.11.3
linter-htmlhint 1.0.2

**Comment by Arcanemagus** [comment]
Does `htmlhint` work on that file from a terminal?

**Comment by fdeneux** [comment]
Yes it does.

`Scan 1 files, found 30 errors in 1 files (35 ms)`

**Comment by Arcanemagus** [comment]
Are you able to share the version of the file with 30 errors that was breaking this?

**Comment by fdeneux** [comment]
I'm not allowed to provide you the full file as it is from a high profile client.
But i could get you the list of the 30 errors listed by `htmlhint` in the terminal if you like.

**Comment by Arcanemagus** [comment]
Unfortunately without the file to test what the difference between the run environments this will be hard to diagnose. The error you originally posted is from `htmlhint`, but it works from the command line so something different between the two environments is what is causing this.

At some point I'll see if I can throw together a large test case to try to reproduce this, unless somebody in @AtomLinter/linter-htmlhint has a different idea?

**Comment by admosity** [comment]
Try this file:

https://raw.githubusercontent.com/admosity/HTMLHint/exit-test-case/test/test.html

I have a feeling it's the same issue as: #50 #45 resulting from atom receiving truncated input.

**Comment by fdeneux** [comment]
Can confirm that the issue can be reproduced with @admosity's file
![error](https://cloud.fabiandeneux.be/s/FS5OEPeqb6/Screen-Shot-2016-02-02-10-47-13.png)

**Comment by santiagomalter** [comment]
Same error here.

**Comment by ivanreese** [comment]
I'm also getting that error on a small-ish file.

<img width="1174" alt="screen shot 2016-02-14 at 5 13 47 pm" src="https://cloud.githubusercontent.com/assets/2061924/13037466/5a44fb44-d33e-11e5-81d9-72be59e4bbe4.png">

**Comment by rugk** [comment]
I also get this error, when editing [this HTML file](https://github.com/diafygi/gethttpsforfree/blob/gh-pages/index.html).

**Comment by Arcanemagus** [comment]
I'm unable to reproduce this with v1.0.3, it's possible that an `atom-linter` library update fixed this... is anyone still able to reproduce?

**Comment by 1000ch** [comment]
I can't reproduce, too.

**Comment by ivanreese** [comment]
Seems to be fixed for me, too.

**Comment by Arcanemagus** [comment]
@fdeneux Are you still able to?

**Comment by rugk** [comment]
I cannot reproduce it too.

**Comment by fdeneux** [comment]
@Arcanemagus Seems to be fixed.

**Comment by igorleao** [comment]
Hi guys,

I'm getting this error with: 
Atom 1.8.0
linter 1.11.4
linter-htmlhint 1.1.4

Does it remain fixed?

**Comment by Arcanemagus** [comment]
@igorleao Can you file a new issue with the information above, and in addition can you include your `htmlhint` version, as well as the file you see this on?

**Comment by igorleao** [comment]
Hi @Arcanemagus
Thanks a lot for your reply.
I've spend some time trying to debug and explore the scenario in order to be accurate on what is wrong. I just created the new issue.

Cheers,
Igor
