### ISSUE TITLE
This message keep showing even when there's no error with my code

### ISSUE THREAD

**Issue by kachunwong628** [AtomLinter/linter-htmlhint#73]
Everytime I save a html file, the following error message is showed:

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Users/aaaaaa/.atom/packages/linter-htmlhint/lib/index.js:61:30
    at process._tickCallback (node.js:368:9)
```

**Comment by Arcanemagus** [comment]
Can you open up Developer Tools and put a breakpoint on [that line](https://github.com/AtomLinter/linter-htmlhint/blob/v1.0.2/lib/index.js#L61) and see what the contents of `output` is?

**Comment by smlombardi** [comment]
I am getting this too.  On my app, the output is:

`"[{"file":"/Users/stevelombardi/github/designsystem/app/modules/resources/templates/resources-tools.html","messages":[{"type":"error","message":"The attribute name of [ viewBox ] must be in lowercase.","raw":" viewBox=\"0 0.388 121.5 89.612\"","evidence":" <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" viewBox=\"0 0.388 121.5 89.612\"><defs><path id=\"a\" d=\"M0 .39h121.5V90H0z\"/></defs><clipPath id=\"b\"><use xlink:href=\"#a\" overflow=\"visible\"/></clipPath><path d=\"M121.5 43.195v4c-.038.217-.086.43-.11.646-.208 1.74-.342 3.492-.628 5.22-.934 5.612-2.953 10.83-5.953 15.653-4.557 7.324-10.716 12.91-18.456 16.723-4.5 2.217-9.248 3.627-14.236 4.2-1.1.128-2.2.242-3.3.363H36.136c-.215-.04-.43-.105-.646-.118-4.305-.27-8.446-1.252-12.393-2.98-8.593-3.76-15-9.853-19.194-18.24C2.043 64.937.86 60.997.358 56.86c-.12-1-.24-1.997-.358-2.995v-3.88c.04-.216.104-.43.117-.647.223-3.73.988-7.35 2.335-10.83 3.625-9.364 9.944-16.31 18.924-20.804 4.66-2.333 9.625-3.56 14.82-3.83 2.542-.133 5.083.01 7.61.348.23.03.56-.07.72-.234 3.634-3.713 7.773-6.73 12.44-9.015 4.527-2.217 9.29-3.646 14.306-4.218C72.452.62 73.635.51 74.817.387h3.64c.237.037.476.08.714.107 1.804.21 3.617.342 5.403.64 5.572.936 10.76 2.936 15.56 5.907 7.36 4.557 12.968 10.724 16.8 18.488 2.22 4.503 3.633 9.252 4.205 14.246.13 1.14.24 2.282.362 3.42M53.565 17.313c.073.096.09.14.122.156 2.507 1.23 4.878 2.678 7.14 4.317.14.103.493.06.665-.048 6.188-3.92 12.896-5.274 20.102-3.996 7.06 1.253 12.807 4.78 17.197 10.416 4.972 6.377 6.867 13.588 5.495 21.61-.92 5.378-3.074 10.202-6.735 14.243-6.68 7.366-15.045 10.413-24.892 9.123-6.062-.794-11.295-3.41-15.626-7.786-5.56-5.615-11.154-11.193-16.73-16.793-.742-.746-1.57-1.346-2.64-1.477-1.868-.23-3.564.704-4.37 2.383-.72 1.5-.628 3.19.934 4.725C40.44 60.285 46.6 66.443 52.81 72.55c1.06 1.045 2.203 2.027 3.408 2.9 4.535 3.294 9.648 5.115 15.185 5.848 4.346.574 8.658.45 12.937-.51 8.162-1.834 14.923-6 20.248-12.428 4.397-5.312 7.056-11.416 7.983-18.27.534-3.937.43-7.855-.33-11.748-1.236-6.33-3.914-11.994-8.205-16.815C95.848 12.334 85.548 8.23 73.29 9.147c-4.714.35-9.174 1.736-13.37 3.933-2.26 1.182-4.38 2.575-6.355 4.232m-3 64.176l-.503-.47c-2.54-2.4-5.096-4.784-7.607-7.214-.486-.47-.933-.7-1.62-.683-2.544.063-5.09.074-7.595-.492-12.46-2.818-19.695-16.365-15.103-28.285 3.622-9.4 13.65-15.123 23.537-13.358 4.432.79 8.322 2.667 11.515 5.96 3.893 4.02 7.903 7.925 11.84 11.904.895.905 1.924 1.318 3.165 1.14 1.604-.228 2.88-.992 3.46-2.565.57-1.548.294-3.014-.878-4.2-4.13-4.186-8.164-8.476-12.462-12.483-8.336-7.775-18.166-10.087-29.038-6.78-14.623 4.442-23.18 19.542-19.84 34.442 3.045 13.576 14.918 23.104 28.81 23.116 3.88.004 7.76.002 11.64 0 .19 0 .383-.017.68-.032\" clip-path=\"url(#b)\" fill=\"#fff\"/></svg>","line":119,"col":95,"rule":{"id":"attr-lowercase","description":"All attribute names must be in lowercase.","link":"https://github.com/yaniswang/HTMLHint/wiki/attr-lowercase"}},{"type":"error","message":"The html element name of [ clipPath ] must be in lowercase.","raw":"<clipPath id=\"b\">","evidence":" <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" viewBox=\"0 0.388 121.5 89.612\"><defs><path id=\"a\" d=\"M0 .39h121.5V90H0z\"/></defs><clipPath id=\"b\"><use xlink:href=\"#a\" overflow=\"visible\"/></clipPath><path d=\"M121.5 43.195v4c-.038.217-.086.43-.11.646-.208 1.74-.342 3.492-.628 5.22-.934 5.612-2.953 10.83-5.953 15.653-4.557 7.324-10.716 12.91-18.456 16.723-4.5 2.217-9.248 3.627-14.236 4.2-1.1.128-2.2.242-3.3.363H36.136c-.215-.04-.43-.105-.646-.118-4.305-.27-8.446-1.252-12.393-2.98-8.593-3.76-15-9.853-19.194-18.24C2.043 64.937.86 60.997.358 56.86c-.12-1-.24-1.997-.358-2.995v-3.88c.04-.216.104-.43.117-.647.223-3.73.988-7.35 2.335-10.83 3.625-9.364 9.944-16.31 18.924-20.804 4.66-2.333 9.625-3.56 14.82-3.83 2.542-.133 5.083.01 7.61.348.23.03.56-.07.72-.234 3.634-3.713 7.773-6.73 12.44-9.015 4.527-2.217 9.29-3.646 14.306-4.218C72.452.62 73.635.51 74.817.387h3.64c.237.037.476.08.714.107 1.804.21 3.617.342 5.403.64 5.572.936 10.76 2.936 15.56 5.907 7.36 4.557 12.968 10.724 16.8 18.488 2.22 4.503 3.633 9.252 4.205 14.246.13 1.14.24 2.282.362 3.42M53.565 17.313c.073.096.09.14.122.156 2.507 1.23 4.878 2.678 7.14 4.317.14.103.493.06.665-.048 6.188-3.92 12.896-5.274 20.102-3.996 7.06 1.253 12.807 4.78 17.197 10.416 4.972 6.377 6.867 13.588 5.495 21.61-.92 5.378-3.074 10.202-6.735 14.243-6.68 7.366-15.045 10.413-24.892 9.123-6.062-.794-11.295-3.41-15.626-7.786-5.56-5.615-11.154-11.193-16.73-16.793-.742-.746-1.57-1.346-2.64-1.477-1.868-.23-3.564.704-4.37 2.383-.72 1.5-.628 3.19.934 4.725C40.44 60.285 46.6 66.443 52.81 72.55c1.06 1.045 2.203 2.027 3.408 2.9 4.535 3.294 9.648 5.115 15.185 5.848 4.346.574 8.658.45 12.937-.51 8.162-1.834 14.923-6 20.248-12.428 4.397-5.312 7.056-11.416 7.983-18.27.534-3.937.43-7.855-.33-11.748-1.236-6.33-3.914-11.994-8.205-16.815C95.848 12.334 85.548 8.23 73.29 9.147c-4.714.35-9.174 1.736-13.37 3.933-2.26 1.182-4.38 2.575-6.355 4.232m-3 64.176l-.503-.47c-2.54-2.4-5.096-4.784-7.607-7.214-.486-.47-.933-.7-1.62-.683-2.544.063-5.09.074-7.595-.492-12.46-2.818-19.695-16.365-15.103-28.285 3.622-9.4 13.65-15.123 23.537-13.358 4.432.79 8.322 2.667 11.515 5.96 3.893 4.02 7.903 7.925 11.84 11.904.895.905 1.924 1.318 3.165 1.14 1.604-.228 2.88-.992 3.46-2.565.57-1.548.294-3.014-.878-4.2-4.13-4.186-8.164-8.476-12.462-12.483-8.336-7.775-18.166-10.087-29.038-6.78-14.623 4.442-23.18 19.542-19.84 34.442 3.045 13.576 14.918 23.104 28.81 23.116 3.88.004 7.76.002 11.64 0 .19 0 .383-.017.68-.032\" clip-path=\"url(#b)\" fill=\"#fff\"/></svg>","line":119,"col":177,"rule":{"id":"tagname-lowercase","description":"All html element names must be in lowercase.","link":"https://github.com/yaniswang/HTMLHint/wiki/tagname-lowercase"}},{"type":"error","message":"The html element name of [ clipPath ] must be in lowercase.","raw":"</clipPath>","evidence":" <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" viewBox=\"0 0.388 121.5 89.612\"><defs><path id=\"a\" d=\"M0 .39h121.5V90H0z\"/></defs><clipPath id=\"b\"><use xlink:href=\"#a\" overflow=\"visible\"/></clipPath><path d=\"M121.5 43.195v4c-.038.217-.086.43-.11.646-.208 1.74-.342 3.492-.628 5.22-.934 5.612-2.953 10.83-5.953 15.653-4.557 7.324-10.716 12.91-18.456 16.723-4.5 2.217-9.248 3.627-14.236 4.2-1.1.128-2.2.242-3.3.363H36.136c-.215-.04-.43-.105-.646-.118-4.305-.27-8.446-1.252-12.393-2.98-8.593-3.76-15-9.853-19.194-18.24C2.043 64.937.86 60.997.358 56.86c-.12-1-.24-1.997-.358-2.995v-3.88c.04-.216.104-.43.117-.647.223-3.73.988-7.35 2.335-10.83 3.625-9.364 9.944-16.31 18.924-20.804 4.66-2.333 9.625-3.56 14.82-3.83 2.542-.133 5.083.01 7.61.348.23.03.56-.07.72-.234 3.634-3.713 7.773-6.73 12.44-9.015 4.527-2.217 9.29-3.646 14.306-4.218C72.452.62 73.635.51 74.817.387h3.64c.237.037.476.08.714.107 1.804.21 3.617.342 5.403.64 5.572.936 10.76 2.936 15.56 5.907 7.36 4.557 12.968 10.724 16.8 18.488 2.22 4.503 3.633 9.252 4.205 14.246.13 1.14.24 2.282.362 3.42M53.565 17.313c.073.096.09.14.122.156 2.507 1.23 4.878 2.678 7.14 4.317.14.103.493.06.665-.048 6.188-3.92 12.896-5.274 20.102-3.996 7.06 1.253 12.807 4.78 17.197 10.416 4.972 6.377 6.867 13.588 5.495 21.61-.92 5.378-3.074 10.202-6.735 14.243-6.68 7.366-15.045 10.413-24.892 9.123-6.062-.794-11.295-3.41-15.626-7.786-5.56-5.615-11.154-11.193-16.73-16.793-.742-.746-1.57-1.346-2.64-1.477-1.868-.23-3.564.704-4.37 2.383-.72 1.5-.628 3.19.934 4.725C40.44 60.285 46.6 66.443 52.81 72.55c1.06 1.045 2.203 2.027 3.408 2.9 4.535 3.294 9.648 5.115 15.185 5.848 4.346.574 8.658.45 12.937-.51 8.162-1.834 14.923-6 20.248-12.428 4.397-5.312 7.056-11.416 7.983-18.27.534-3.937.43-7.855-.33-11.748-1.236-6.33-3.914-11.994-8.205-16.815C95.848 12.334 85.548 8.23 73.29 9.147c-4.714.35-9.174 1.736-13.37 3.933-2.26 1.182-4.38 2.575-6.355 4.232m-3 64.176l-.503-.47c-2.54-2.4-5.096-4.784-7.607-7.214-.486-.47-.933-.7-1.62-.683-2.544.063-5.09.074-7.595-.492-12.46-2.818-19.695-16.365-15.103-28.285 3.622-9.4 13.65-15.123 23.537-13.358 4.432.79 8.322 2.667 11.515 5.96 3.893 4.02 7.903 7.925 11.84 11.904.895.905 1.924 1.318 3.165 1.14 1.604-.228 2.88-"`

**Comment by ivanreese** [comment]
I get this error on every file that contains some HTML + some other markup format. Eg: all of my erb templates in a rails project.

**Comment by RedSentry** [comment]
Same here getting this error

**Comment by deftOfCenter** [comment]
Same

**Comment by fwd079** [comment]
Oh okay so its already reported. I think I need to disable htmllint for RoR projects till its fixed.

**Comment by jerone** [comment]
Same issue on normal HTML files.

_Atom 1.7.0
linter-htmlhint 1.1.2
Windows 8.1 x64_

**Comment by jerone** [comment]
[**@Arcanemagus**](https://github.com/Arcanemagus) commented on [1 feb. 2016 08:51 CET](https://github.com/AtomLinter/linter-htmlhint/issues/73#issuecomment-177829562 "2016-02-01T07:51:06Z - Replied by Github Comment Enhancer"):
> Can you open up Developer Tools and put a breakpoint on [that line](https://github.com/AtomLinter/linter-htmlhint/blob/v1.0.2/lib/index.js#L61) and see what the contents of `output` is?

![linter-htmlhint](https://cloud.githubusercontent.com/assets/55841/14521705/fcfa3a8c-022a-11e6-8a29-8211e681e42f.png)

**Comment by Arcanemagus** [comment]
@jerone You're almost certainly hitting #99, which at it's root I've filed https://github.com/atom/atom/issues/11471 to figure out what is going on.

**Comment by Arcanemagus** [comment]
Atom v1.7.1 (And v1.8.0-beta1) has been released which should fix this. If you are still having issues please re-open this or file a new issue.
