### ISSUE TITLE
could check "handlebars/spacebars" in html file (from  Meteor Blaze)?

### ISSUE THREAD

**Issue by thearabbit** [AtomLinter/linter-htmlhint#82]
I come form `Meteor JS`, I have problem with `balze/spacebars/handlebars`.
```js
<body>
  <h1>Welcome to Meteor!</h1>

  {{> hello}}
</body>
```
Please help me.

**Comment by Arcanemagus** [comment]
Rather than removing support for scopes (languages) that `htmlhint` doesn't support, @johnwebbcole's solution to issues like this is to add the errors that crop up to the ignored errors list.

**Comment by thearabbit** [comment]
Thanks for your reply.
