### ISSUE TITLE
.htmlhintrc in users home

### ISSUE THREAD

**Issue by arielnoname** [AtomLinter/linter-htmlhint#87]
Maybe its a good idea to put .htmlhintrc in ~/.atom directory for a global config?

**Comment by Arcanemagus** [comment]
[Currently](https://github.com/AtomLinter/linter-htmlhint/blob/v1.0.3/lib/index.js#L53) `.htmlhintrc` is searched for in the current file's directory, and all parent folders. If for some reason you want a global config, try placing it in a folder that is a parent to all of your projects.
