### ISSUE TITLE
Error: Process execution timed out

### ISSUE THREAD

**Issue by davidafuller01** [AtomLinter/linter-htmlhint#92]
Regularly getting the following error:
`Error: Process execution timed out
    at /Users/myUsername/.atom/packages/linter-htmlhint/node_modules/atom-linter/lib/helpers.js:79:18`

Atom 1.5.4
linter 1.11.3
linter-htmlhint 1.1.0

(I do have node.js installed on my machine, but hopefully that doesn't matter.)

Example file: [2016-ncaa-bracket-iframe.txt](https://github.com/AtomLinter/linter-htmlhint/files/176233/2016-ncaa-bracket-iframe.txt)

**Comment by Arcanemagus** [comment]
Closing, #112 should make this irrelevant.
