### ISSUE TITLE
Native attribute bindings shows up as an error

### ISSUE THREAD

**Issue by VikramTiwari** [AtomLinter/linter-htmlhint#94]
for example:
`<img src$="{{image}}">` shows up as error message `Special characters must be escaped : [ < ]`

**Comment by johnwebbcole** [comment]
does htmlhint show that as an error if you run it via the command line?

**Comment by Arcanemagus** [comment]
Any update @VikramTiwari?

**Comment by VikramTiwari** [comment]
Hey guys! Sorry for totally losing track of this. Just tested it with a sample, and yes, it shows that as error as well.
