### ISSUE TITLE
Update htmlhint to 0.9.13

### ISSUE THREAD

**Issue by coliff** [AtomLinter/linter-htmlhint#95]
Can htmlhint be updated to 0.9.13 in package.json? That is the latest version available.

REF: https://github.com/yaniswang/HTMLHint/blob/master/CHANGE.md

**Comment by johnwebbcole** [comment]
It's using ~0.9.12, so if you reinstall it should pull 0.9.13

**Comment by coliff** [comment]
Ah I see. thanks!
