### ISSUE TITLE
Add a CHANGELOG.md

### ISSUE THREAD

**Issue by coliff** [AtomLinter/linter-htmlhint#96]
It'd be nice to see a CHANGELOG.md added. Would be interesting to see what's changed with each update of this package.

I think if you add a CHANGELOG.md to the directory it'll be viewable from the Settings of this package from within Atom.

**Comment by johnwebbcole** [comment]
+1 Is there a format for the change-log within atom?

**Comment by coliff** [comment]
It simply needs to be labelled CHANGELOG.md and be in the root directory. Some info here on changelogs in general: http://keepachangelog.com/

**Comment by Arcanemagus** [comment]
FYI: I use [github-changelog-generator](https://github.com/skywinder/github-changelog-generator/) on most of the other linters. It's not perfect, but it gets the job done. If you find something better I would love to hear about it :wink:.

**Comment by Arcanemagus** [comment]
Also, just a note: The changelog shown inside Atom is as of the state it was in when the installed version was tagged, it doesn't automatically follow master.

**Comment by 1000ch** [comment]
Added :ok_hand: 295391b
